dist: trusty
sudo: required
language: python
install:
  - scripts/install-vault-${VAULT_BRANCH}.sh
  - pip install tox
script:
  - export PATH=$HOME/bin:$PATH
  - tox
env:
  - TOXENV=py27 VAULT_BRANCH=release
  - TOXENV=py34 VAULT_BRANCH=release
  - TOXENV=py34 VAULT_BRANCH=head
matrix:
  allow_failures:
    - env: TOXENV=py34 VAULT_BRANCH=head
