dist: trusty
sudo: required
language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
matrix:
  include:
    - python: '2.7'
      env: TOXENV=py27 VAULT_BRANCH=release
    - python: '3.5'
      env: TOXENV=py35 VAULT_BRANCH=release
  allow_failures:
    - python: '2.6'
      env: TOXENV=py26 VAULT_BRANCH=release
    - python: '3.5'
      env: TOXENV=py35 VAULT_BRANCH=head
install:
  - scripts/install-vault-${VAULT_BRANCH}.sh
  - pip install tox
script:
  - export PATH=$HOME/bin:$PATH
  - tox
